version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Framework
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: Framework
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./user-service/db/migrations:/app/user-service/db/migrations

  toy-service:
    build: ./toy-service
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: Framework
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./toy-service/db/migrations:/app/toy-service/db/migrations

volumes:
  postgres_data:
