version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Framework
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
      dockerfile: ../user-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: user_db
      JWT_SECRET: your_secret_key_here
    volumes:
      - ./user-service/db/migrations:/app/db/migrations

  toy-service:
    build:
      context: ./toy-service
      dockerfile: ../toy-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
      - user-service
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: toy_db
      JWT_SECRET: your_secret_key_here
    volumes:
      - ./toy-service/db/migrations:/app/db/migrations
  
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - toy-service

volumes:
  postgres_data: